"""Versioned public boundary for Ducking's reusable audio engine."""

from .contracts import (
    CORE_API_VERSION,
    ENGINE_BASELINE_COMMIT,
    AudioCore,
    AudioMetadata,
    CoreErrorCode,
    CoreProcessingError,
    CoreWarning,
    EditInterval,
    OutputAsset,
    OutputKind,
    OutputTargets,
    ProcessingPreset,
    ProcessingSettings,
    QualityMeasurements,
    RenderRequest,
    RenderResult,
    SourceAsset,
    SourceRole,
    ThemeAssets,
    TrimSuggestion,
    WarningCode,
    contract_to_dict,
)

__all__ = [
    "CORE_API_VERSION",
    "ENGINE_BASELINE_COMMIT",
    "AudioCore",
    "AudioMetadata",
    "CoreErrorCode",
    "CoreProcessingError",
    "CoreWarning",
    "EditInterval",
    "OutputAsset",
    "OutputKind",
    "OutputTargets",
    "ProcessingPreset",
    "ProcessingSettings",
    "QualityMeasurements",
    "RenderRequest",
    "RenderResult",
    "SourceAsset",
    "SourceRole",
    "ThemeAssets",
    "TrimSuggestion",
    "WarningCode",
    "contract_to_dict",
]
